site_name: UrbanFootprint 1.5

theme: readthedocs
use_directory_urls: false

pages:
- User Guide:
  - Introduction: 'index.md'
  - System Requirements: 'system_requirements.md'
  - User Interface Overview:
    - Site Map: 'site_map.md'
    - 1. Top Section Menu Pane: 'top_section_menu_pane.md'
    - 2. Layer Management Window: 'layer_management.md'
    - 3. Map View: 'map_tool_bar.md'
    - 4. Scenario Editor: 'scenario_editor.md'
    - 5. Analysis Modules: 'analysis_modules.md'
- User Manager: 'user_manager.md'
- ArcGIS Integration: 'arc_plugin.md'
- Base Data Preparation: 'data_preparation.md'
- User Support: 'user_support.md'

copyright: © 2016 Calthorpe Analytics
